apiVersion: v1
kind: Secret
metadata:
  name: saga-secrets
  namespace: autoflow
type: Opaque
stringData:
  NODE_ENV: production
  APP_PORT: "3002"

  DATABASE_HOST: "REPLACE_ME"
  DATABASE_PORT: "5432"
  DATABASE_USER: saga_user
  DATABASE_PASSWORD: "REPLACE_ME"
  DATABASE_NAME: saga

  RABBITMQ_URL: "amqp://admin:REPLACE_ME@rabbitmq.autoflow.svc.cluster.local:5672"

  ORDER_SERVICE_URL: "http://order-service.autoflow.svc.cluster.local:3001"
