sonar.projectKey=kaikelfalcao_autoflow-saga-orchestrator
sonar.organization=kaikelfalcao

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=autoflow-saga-orchestrator
#sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src,features
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,test/**/*,features/**/*
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=  **/*.spec.ts,  **/*.test.ts,  **/node_modules/**,  **/dist/**,  **/coverage/**,  **/migrations/**,  **/*.dto.ts,  **/*.module.ts,  **/*.schema.ts,  **/*.orm-entity.ts,  **/main.ts,  **/newrelic.js,  **/data-source.ts,  **/typeorm.datasource.ts
sonar.coverage.exclusions=  **/*.dto.ts,  **/*.module.ts,  **/*.schema.ts,  **/*.orm-entity.ts,  **/main.ts,  **/migrations/**,  **/newrelic.js,  **/data-source.ts,  **/typeorm.datasource.ts,  **/winston.config.ts,  **/env.config.ts,  **/env.schema.ts,  **/__mocks__/**
