apiVersion: v1
kind: Service
metadata:
  name: saga-orchestrator
  namespace: autoflow
spec:
  selector:
    app: saga-orchestrator
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
  type: ClusterIP
